// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: ice_cream.proto

package ice_cream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IceCreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scoops int32  `protobuf:"varint,1,opt,name=scoops,proto3" json:"scoops,omitempty"`
	Flavor string `protobuf:"bytes,2,opt,name=flavor,proto3" json:"flavor,omitempty"`
}

func (x *IceCreamRequest) Reset() {
	*x = IceCreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ice_cream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IceCreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCreamRequest) ProtoMessage() {}

func (x *IceCreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ice_cream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCreamRequest.ProtoReflect.Descriptor instead.
func (*IceCreamRequest) Descriptor() ([]byte, []int) {
	return file_ice_cream_proto_rawDescGZIP(), []int{0}
}

func (x *IceCreamRequest) GetScoops() int32 {
	if x != nil {
		return x.Scoops
	}
	return 0
}

func (x *IceCreamRequest) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

type IceCreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IceCreamResponse) Reset() {
	*x = IceCreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ice_cream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IceCreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCreamResponse) ProtoMessage() {}

func (x *IceCreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ice_cream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCreamResponse.ProtoReflect.Descriptor instead.
func (*IceCreamResponse) Descriptor() ([]byte, []int) {
	return file_ice_cream_proto_rawDescGZIP(), []int{1}
}

func (x *IceCreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ice_cream_proto protoreflect.FileDescriptor

var file_ice_cream_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x41, 0x0a, 0x0f, 0x49, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x6f, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6c, 0x61, 0x76, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6c,
	0x61, 0x76, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x10, 0x49, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x40, 0x0a, 0x08, 0x49, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x34,
	0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x10, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ice_cream_proto_rawDescOnce sync.Once
	file_ice_cream_proto_rawDescData = file_ice_cream_proto_rawDesc
)

func file_ice_cream_proto_rawDescGZIP() []byte {
	file_ice_cream_proto_rawDescOnce.Do(func() {
		file_ice_cream_proto_rawDescData = protoimpl.X.CompressGZIP(file_ice_cream_proto_rawDescData)
	})
	return file_ice_cream_proto_rawDescData
}

var file_ice_cream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ice_cream_proto_goTypes = []interface{}{
	(*IceCreamRequest)(nil),  // 0: IceCreamRequest
	(*IceCreamResponse)(nil), // 1: IceCreamResponse
}
var file_ice_cream_proto_depIdxs = []int32{
	0, // 0: IceCream.OrderIceCream:input_type -> IceCreamRequest
	1, // 1: IceCream.OrderIceCream:output_type -> IceCreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ice_cream_proto_init() }
func file_ice_cream_proto_init() {
	if File_ice_cream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ice_cream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IceCreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ice_cream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IceCreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ice_cream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ice_cream_proto_goTypes,
		DependencyIndexes: file_ice_cream_proto_depIdxs,
		MessageInfos:      file_ice_cream_proto_msgTypes,
	}.Build()
	File_ice_cream_proto = out.File
	file_ice_cream_proto_rawDesc = nil
	file_ice_cream_proto_goTypes = nil
	file_ice_cream_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IceCreamClient is the client API for IceCream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IceCreamClient interface {
	OrderIceCream(ctx context.Context, in *IceCreamRequest, opts ...grpc.CallOption) (*IceCreamResponse, error)
}

type iceCreamClient struct {
	cc grpc.ClientConnInterface
}

func NewIceCreamClient(cc grpc.ClientConnInterface) IceCreamClient {
	return &iceCreamClient{cc}
}

func (c *iceCreamClient) OrderIceCream(ctx context.Context, in *IceCreamRequest, opts ...grpc.CallOption) (*IceCreamResponse, error) {
	out := new(IceCreamResponse)
	err := c.cc.Invoke(ctx, "/IceCream/OrderIceCream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IceCreamServer is the server API for IceCream service.
type IceCreamServer interface {
	OrderIceCream(context.Context, *IceCreamRequest) (*IceCreamResponse, error)
}

// UnimplementedIceCreamServer can be embedded to have forward compatible implementations.
type UnimplementedIceCreamServer struct {
}

func (*UnimplementedIceCreamServer) OrderIceCream(context.Context, *IceCreamRequest) (*IceCreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderIceCream not implemented")
}

func RegisterIceCreamServer(s *grpc.Server, srv IceCreamServer) {
	s.RegisterService(&_IceCream_serviceDesc, srv)
}

func _IceCream_OrderIceCream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IceCreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IceCreamServer).OrderIceCream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IceCream/OrderIceCream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IceCreamServer).OrderIceCream(ctx, req.(*IceCreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IceCream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IceCream",
	HandlerType: (*IceCreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrderIceCream",
			Handler:    _IceCream_OrderIceCream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ice_cream.proto",
}
